### ISSUE TITLE
`set -eu` translated as empty `(do)`

### ISSUE THREAD

**Issue by dundalek** [pesterhazy/bash2bb#4]
I have some scripts starting with `set -eu`. Given babashka has a sane default by throwing on error, it makes sense the setting can be ignored.

This is a minor detail, output ends up with extraneous `(do)` which could be omitted.

```sh
set -eu
echo a
```

```clj
#!/usr/bin/env bb

(require (quote [babashka.process :refer [shell pipeline pb]]))
(do)
(shell "echo" "a")
```

**Comment by pesterhazy** [comment]
Fixed! I had a baked in assumption in the code that every ast element translated into exactly one form. Removing this (incorrect) assumption required a bit of refactoring.
